### ISSUE TITLE
QC Checklist

### ISSUE THREAD

**Issue by DanceParty** [KeevanDance/CFThrowdown-lite#28]
**Admin**

- [ ] Clicking logout should logout the user and return to the public page removing access to write data
 
Workouts:
- [ ] Clicking workouts should show all workouts where default sort is RX (or scaled if RX is not an option)
- [ ] Clicking on a workout should take you to the details page of that workout displaying name, division, gender, score type, and steps
- [ ] Clicking on Add Workout should allow you to enter and submit a new workout. This should add the workout to all existing competitors of the same division and gender and to the division that was selected
- [ ] Clicking "submit workout scores" should iterate through all competitors apart of this workout and place them according to their score for both Timed and Weighted workouts

Competitors:
- [ ] Click on Competitors should show all competitors with options to filter by gender and division
- [ ] Clicking Add Competitor should allow you to create a new competitor. This should add all of the existing relevant workouts to the scores array for that competitor based on division and gender
- [ ] Clicking on a Competitor should show more information for that competitor
- [ ] Clicking on Edit Mode should flip the button text to Save Changes and allow you to edit every part of the competitor. Updating gender and/or division should alter the scores array to only have workouts that match the combination

Divisions:
- [ ] Clicking on Divisions should show all available divisions
- [ ] clicking on Add Division should give you the option to add a division
- [ ] clicking on a division should give you a button to then delete the division
- [ ] clicking the delete this division button should delete the division (including workoutIds under that division), workouts associated with this division, and update competitors removing scores and division for those that are associated with this division

**Public**

- [ ] Clicking Login here should take the user to a login page where they can enter admin credentials and be taken to an admin home page

Leaderboard:

Workouts: 
- [ ] Clicking Workouts should display all of the workouts for the filter set (default is Men, RX)

Competitors:
- [ ] Clicking on Competitors should show all competitors allowing for the filtering by gender and division
